[build-system]
requires = ["setuptools>=42", "websockets"]
build-backend = "setuptools.build_meta"

[project]
name = "OneBotConnecter"
version = "0.1.1"
authors = [
  { name="Sugar51243", email="1733682365@qq.com" },
]
description = "基于websocket(服务器正向)连接的onebot11通用python接口"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {file = "LICENSE"}


[project.urls]
Homepage = "https://github.com/Sugar51243/OneBotConnecter"
Issues = "https://github.com/Sugar51243/OneBotConnecter/issues"